image: tingefr/picobuild:0.2.0

services:
  - docker:20.10.9-dind

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - cp $SSH_CONFIG ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - cp $SSH_PRIVATE_KEY ~/.ssh/default.pem
  - chmod 600 ~/.ssh/default.pem
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  
picogalaxy:
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - export BUILD_VERSION=$CI_COMMIT_REF_NAME
    - export ANSIBLE_FORCE_COLOR=true
    - cd deploy
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -i hosts playbook.yml
